var i=10;
var b=true;
var a;
var n=null;
var book={title:"js"};
console.log(i.toString());
console.log(b.toString());
// console.log(n.toString());
console.log(book.toString());
// console.log(a.toString());
console.log("===========================");
console.log(String(i));
console.log(String(b));
console.log(String(n));
console.log(String(a));
console.log(String(book));
console.log("===========================");
console.log(""+i);
console.log(""+b);
console.log(""+a);
console.log(""+n);
console.log(""+book);